pipeline:
  test:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t agenttestdocker .
      - docker run --rm agenttestdocker