version: '3'

services:
  dev:
    stdin_open: true
    tty: true
    build: 
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "15000:5000"
    volumes:
      - .:/app
    networks:
      seaweedfs: {}
      db: {}