// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkNet.FileProvider.Models;

namespace WorkNet.FileProvider.Migrations
{
    [DbContext(typeof(FileEntryContext))]
    [Migration("20190722100315_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WorkNet.FileProvider.Models.FileEntry", b =>
                {
                    b.Property<int>("FileEntryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ETag");

                    b.Property<string>("ExtName");

                    b.Property<string>("FileName");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Namespace");

                    b.Property<string>("SeaweedId");

                    b.Property<int>("Size");

                    b.Property<List<string>>("Tags");

                    b.HasKey("FileEntryID");

                    b.ToTable("FileEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
