// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkNet.Server.Models;

namespace WorkNet.Server.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20190730032743_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WorkNet.Server.Models.Executor", b =>
                {
                    b.Property<long>("ExecutorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Execution");

                    b.Property<string>("Image");

                    b.HasKey("ExecutorId");

                    b.ToTable("Executors");
                });

            modelBuilder.Entity("WorkNet.Server.Models.SingleTask", b =>
                {
                    b.Property<long>("SingleTaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Parameters")
                        .HasColumnType("json");

                    b.Property<int[]>("Pulls");

                    b.Property<int?>("Result");

                    b.Property<int?>("TaskGroupId");

                    b.HasKey("SingleTaskId");

                    b.HasIndex("TaskGroupId");

                    b.ToTable("SingleTask");
                });

            modelBuilder.Entity("WorkNet.Server.Models.TaskGroup", b =>
                {
                    b.Property<int>("TaskGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Assignment");

                    b.Property<int>("Status");

                    b.Property<int>("UserTaskId");

                    b.HasKey("TaskGroupId");

                    b.HasIndex("UserTaskId");

                    b.ToTable("TaskGroups");
                });

            modelBuilder.Entity("WorkNet.Server.Models.UserTask", b =>
                {
                    b.Property<int>("UserTaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Execution");

                    b.Property<int?>("Executor");

                    b.Property<string>("Image");

                    b.Property<int>("SubFinished");

                    b.Property<int>("SubTotal");

                    b.Property<DateTime>("SubmitTime");

                    b.HasKey("UserTaskId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("WorkNet.Server.Models.SingleTask", b =>
                {
                    b.HasOne("WorkNet.Server.Models.TaskGroup")
                        .WithMany("SingleTasks")
                        .HasForeignKey("TaskGroupId");
                });

            modelBuilder.Entity("WorkNet.Server.Models.TaskGroup", b =>
                {
                    b.HasOne("WorkNet.Server.Models.UserTask", "UserTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
