version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      worknet: {}
    ports:
      - 15672:15672
      - 5672:5672
  database:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
      
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      worknet: {}
    
  
networks:
  worknet:
