version: '3'
services: 
  agent:
    restart: always
    build:
      context: ..
      dockerfile: docker/Agent.DockerFile
    volumes:
      - /home/worknode/data:/app/data
      - /home/worknode/appsettings.json:/app/appsettings.json
      - /var/run/docker.sock:/var/run/docker.sock
    
    